import type { PublicPostCard } from "@/helper/public-post-service";

/** Demo cards when DB is empty or unreachable (layout preview). */
export const HOME_SAMPLE_FEED: PublicPostCard[] = [
  {
    id: "sample-1",
    slug: "sample-local-news-1",
    title: "Local administration launches road repair plan",
    excerpt:
      "Repair work on main city roads will begin soon. Residents are asked for their cooperation.",
    categoryName: "City",
    subcategoryName: "",
    subcategorySlug: "",
    isTrending: true,
    updatedAt: new Date().toISOString(),
    mediaType: "image" as const,
    imageUrl: "",
    youtubeUrl: "",
    viewCount: 0,
    commentCount: 0,
    likeCount: 0,
  },
  {
    id: "sample-2",
    slug: "sample-crime-courts-1",
    title: "Court sets next hearing date in case",
    excerpt: "After hearing arguments from lawyers, the judge adjourned proceedings.",
    categoryName: "Crime & Courts",
    subcategoryName: "",
    subcategorySlug: "",
    isTrending: false,
    updatedAt: new Date().toISOString(),
    mediaType: "image" as const,
    imageUrl: "",
    youtubeUrl: "",
    viewCount: 0,
    commentCount: 0,
    likeCount: 0,
  },
  {
    id: "sample-3",
    slug: "sample-business-1",
    title: "Investor interest grows at startup summit",
    excerpt: "Young entrepreneurs pitched ideas; several MOUs were signed.",
    categoryName: "Business",
    subcategoryName: "",
    subcategorySlug: "",
    isTrending: true,
    updatedAt: new Date().toISOString(),
    mediaType: "image" as const,
    imageUrl: "",
    youtubeUrl: "",
    viewCount: 0,
    commentCount: 0,
    likeCount: 0,
  },
];
